name: Content Request
description: Request new content or improvements to existing documentation
title: "[REQUEST] "
labels: ["enhancement", "content"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting new content or improvements! Your ideas help make this repository more valuable for the NFP community.

  - type: dropdown
    id: request-type
    attributes:
      label: Type of Request
      description: What kind of content are you requesting?
      options:
        - New venture documentation
        - New template or framework
        - Improvement to existing content
        - Missing case study or example
        - Translation or accessibility improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: request-description
    attributes:
      label: Request Description
      description: What would you like to see added or improved?
      placeholder: Describe your content request in detail...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this content help you or other NFP practitioners?
      placeholder: Explain the practical application and benefit...
    validations:
      required: true

  - type: textarea
    id: existing-examples
    attributes:
      label: Existing Examples or Resources
      description: Do you have examples or resources that could inform this content?
      placeholder: Links, documents, or examples that might be helpful...
    validations:
      required: false

  - type: textarea
    id: contribution-offer
    attributes:
      label: Contribution Offer
      description: Are you willing to contribute to creating this content?
      placeholder: How could you help develop this content?
    validations:
      required: false

  - type: checkboxes
    id: alignment
    attributes:
      label: Alignment Check
      options:
        - label: This request aligns with NFP innovation and scaling objectives
          required: true
        - label: I believe this would benefit multiple organizations, not just mine
          required: true
        - label: I have checked that similar content doesn't already exist in the repository
          required: true 